Auth
jetbridge/smorest-crud pull request #1
Opened 2020-02-11 15:33 UTC by revmischa

Rename flask-crud to smorest-crud. Add access check support with flask-jwt-extended.

Because this guy won't give up flask-crud: https://github.com/plumdog/flask_crud/issues/2
And flask-rest-api got renamed to flask-smorest

2020-02-11 15:39 UTC, gnudeb approved these changes

2020-02-11 15:49 UTC, AnneMedvedeva approved these changes

2020-02-11 18:17 UTC, adamszeptycki approved these changes

2020-02-11 18:17 UTC, adamszeptycki commented on setup.py
> +    license="WTFPL",
MIT license please

2020-02-11 18:17 UTC, adamszeptycki requested changes
change license

2020-02-14 13:08 UTC, paveu-piotrowski approved these changes

2020-02-14 15:28 UTC, adamszeptycki approved these changes
LGTM!

2020-02-14 15:29 UTC, merged